### PR TITLE
Highligh properly tags in high-tag-number-form

### PR DESCRIPTION
**Pull request by suttod**

### CODE REVIEW

**Comment by suttod** [comment]
Hi,

can you provide any information, why the fix has been rejected?
Should I merge it with your latest updates?

Thanks,
suttod

**Comment by lapo-luchini** [comment]
Sorry I might have mis-clicked, I never wanted to close this… 😳 and it seems I cannot re-open this.

image

Oh, I guess GitHub did this automatically when I renamed the "master" branch to "trunk".

**Comment by lapo-luchini** [comment]
So then, yes please merge it with latest "trunk" changes and we'll see if that way this PR can be re-opened. (or you can create a new one)

Also, do you have any example ASN.1 snippet to properly test the new feature?
(if you want, you can add that to `test.js` yourself, or I can do it later)

**Comment by lapo-luchini** [comment]
Don't worry, I can (test and) merge this anyways.

**Comment by lapo-luchini** [comment]
I tested this using a BER with a lot of unnecessary zeroes at the start of both tag and length tags: `30 09 9F 80FFFF 7F 820001 01`.
Without this PR:
image
after your PR:
image

**Comment by lapo-luchini** [comment]
Your original commit got re-committed as 352bc9f44a0de4879531c4cd1b6eccce363ab845 (keeping your authorship in metadata).

**Pull request closed without merging**
