### PR TITLE
Add relative OID support

### PR DESCRIPTION
**Pull request by mistial-dev**
Add support for relative OID encoding.

https://www.oss.com/asn1/resources/asn1-made-simple/asn1-quick-reference/relative-oid.html

### CODE REVIEW

**Comment by lapo-luchini** [comment]
Hi, thanks for the patch! I imported it in branch [github-56](https://github.com/lapo-luchini/asn1js/compare/github-56) (I'm using mtn to track asn1js, not git, so I had to re-commit it in my name, but I kept all the content and metadata identical to your commit).
I also added a new test case from official specs and it is [failing](https://github.com/lapo-luchini/asn1js/actions/runs/3464486544/jobs/5786069341).

**Comment by mistial-dev** [comment]
I'll take a look at the test case and see what's going on.  I was having a hard time finding the official specs, just other implementations and things talking about it.

**Comment by lapo-luchini** [comment]
I just fixed it, take a look at 1fb6f67f457c0eb63a8a8725dc1cce47d705fd3a to have a double-check then I can merge and close this PR.

**Comment by mistial-dev** [comment]
That's definitely a simpler way to handle it.  It looks good on my end.

Thanks for catching that.

**Comment by lapo-luchini** [comment]
Merged in f5ba28053aa597638a53cbdbe6930eb3cfd7bb97.
Thanks!

**Pull request closed without merging**
