### PR TITLE
Cleaner hover icon for current selected node

### PR DESCRIPTION
**Pull request by olibu**
This is a small fix to highlight to current selected node without hiding the object type.
Additionally to that the highlight is set in case of hovering at the hex view, too.

It now looks like this:
image

### CODE REVIEW

**Comment by lapo-luchini** [comment]
That red icon was a leftover of an experiment to have a hover-menu to click upon, was never intended to be there. I recently removed it with the "context menu" #82 changes.
I also added some `bgcolor` highlight in 6052316abd565682e7f115ea9fef95e379a5a362.
Do you think this is still needed?
If you have suggestions, can you base them on latest code from `esm` branch?
Thanks!

**Comment by olibu** [comment]
I don't think that this is required any more as of the current esm branch.

**Comment by olibu** [comment]
I have concept draft for a new interactive tree view based on the latest esm branch in my repository.
https://github.com/olibu/asn1js/tree/treeview

@lapo-luchini
What do you think about it.

**Comment by lapo-luchini** [comment]
Hi!
I really like the "real tree" look, I'm not very fond of the ⊕ icon, seems a bit too cumbersone (I mean too "noticeable" in regards of the actual text), but that's a minor issue (I think it can be improved easily with smaller size or with less contrast).

Something funny happened with distances between elements (my [2.0.1](https://rawcdn.githack.com/lapo-luchini/asn1js/2.0.1/index.html#MIIBfzCCATGgAwIBAgIUfI5kSdcO2S0-LkpdL3b2VUJG10YwBQYDK2VwMDUxCzAJBgNVBAYTAklUMQ8wDQYDVQQHDAZNaWxhbm8xFTATBgNVBAMMDFRlc3QgZWQyNTUxOTAeFw0yMDA5MDIxMzI1MjZaFw0zMDA5MDIxMzI1MjZaMDUxCzAJBgNVBAYTAklUMQ8wDQYDVQQHDAZNaWxhbm8xFTATBgNVBAMMDFRlc3QgZWQyNTUxOTAqMAUGAytlcAMhADupL_3LF2beQKKS95PeMPgKI6gxIV3QB9hjJC7_aCGFo1MwUTAdBgNVHQ4EFgQUa6W9z536I1l4EmQXrh5y2JqASugwHwYDVR0jBBgwFoAUa6W9z536I1l4EmQXrh5y2JqASugwDwYDVR0TAQH_BAUwAwEB_zAFBgMrZXADQQBvc3e-KJZaMzbX5TT9kPP9QH8fAvkAV_IWDxZrBL9lhLaY0tDSv0zWbw624uidBKPgmVD5wm3ec60dNVeFZYYG) vs your [treeview](https://rawcdn.githack.com/olibu/asn1js/feature/treeview/index.html#MIIBfzCCATGgAwIBAgIUfI5kSdcO2S0-LkpdL3b2VUJG10YwBQYDK2VwMDUxCzAJBgNVBAYTAklUMQ8wDQYDVQQHDAZNaWxhbm8xFTATBgNVBAMMDFRlc3QgZWQyNTUxOTAeFw0yMDA5MDIxMzI1MjZaFw0zMDA5MDIxMzI1MjZaMDUxCzAJBgNVBAYTAklUMQ8wDQYDVQQHDAZNaWxhbm8xFTATBgNVBAMMDFRlc3QgZWQyNTUxOTAqMAUGAytlcAMhADupL_3LF2beQKKS95PeMPgKI6gxIV3QB9hjJC7_aCGFo1MwUTAdBgNVHQ4EFgQUa6W9z536I1l4EmQXrh5y2JqASugwHwYDVR0jBBgwFoAUa6W9z536I1l4EmQXrh5y2JqASugwDwYDVR0TAQH_BAUwAwEB_zAFBgMrZXADQQBvc3e-KJZaMzbX5TT9kPP9QH8fAvkAV_IWDxZrBL9lhLaY0tDSv0zWbw624uidBKPgmVD5wm3ec60dNVeFZYYG)):
image
image

**Comment by lapo-luchini** [comment]
> I don't think that this is required any more

Okay! Then (if I didn't misunderstand your comment, else feel free to re-open it) I'll close this PR and we can talk about `feature/treeview` in #87. 👍🏼

**Pull request closed without merging**
